// <auto-generated />
namespace Melissa_Scott_9189_IPG521_FA1_Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class B : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(B));
        
        string IMigrationMetadata.Id
        {
            get { return "202111121131291_B"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
